version: "3"

services:
  app:
    build: .
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ".:/app/"
    links:
      - db
      - channel_layer
    depends_on:
      - db
      - channel_layer
  migration:
    build: .
    env_file:
      - .env
    command: sh -c "python manage.py makemigrations && python manage.py migrate"
    volumes:
      - ".:/app/"
    links:
      - db
      - channel_layer
    depends_on:
      - db
      - channel_layer
  db:
    image: postgres:12
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - ./cache/db_dev:/var/lib/postgresql/data
  channel_layer:
    image: redis
    ports:
      - "6379:6379"

volumes:
  db_dev: {}