version: "3"

services:
#  app:
#    build: .
#    env_file:
#      - .env.development
##    command: python manage.py runserver 8000
#    ports:
#      - "8000:8000"
#    volumes:
#      - ".:/app/"
#    tty: true
#    links:
#      - db
#      - channel_layer
#    depends_on:
#      - db
#      - channel_layer
  migration:
    build: .
    env_file:
      - .env.local
    command: sh -c "python manage.py makemigrations && python manage.py migrate"
    links:
      - db
      - channel_layer
    depends_on:
      - db
      - channel_layer
  db:
    image: postgres:12
    ports:
      - "5433:5432"
    env_file:
      - .env.local
    volumes:
      - ./cache/db_dev:/var/lib/postgresql/data
  channel_layer:
    image: redis
    ports:
      - "6379:6379"

volumes:
  db_dev: {}