# Generated by Django 3.2.8 on 2021-10-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_confirmtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmtoken',
            name='token',
            field=models.CharField(max_length=60, unique=True, verbose_name='Token'),
        ),
    ]
