# Generated by Django 3.2.8 on 2021-10-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_confirmtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmtoken',
            name='token',
            field=models.CharField(max_length=80, unique=True, verbose_name='Token'),
        ),
    ]
