# Generated by Django 3.2.8 on 2021-10-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_confirmtoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmtoken',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
