# Generated by Django 3.2.8 on 2021-10-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
